      MODULE PCFI_PT
      INTEGER :: N_ASIMINA, NPCFI
      CHARACTER, DIMENSION(:), ALLOCATABLE :: PCFINAME
      INTEGER, DIMENSION(:), ALLOCATABLE :: NCSFPCFI
            
      END MODULE PCFI_PT
      
